### ISSUE TITLE
Broken link - https://dl.dropboxusercontent.com/u/732913/dream-code.mov

### ISSUE THREAD

**Issue by samyakbhuta** [noBackend/nobackend.org#19]
On page http://nobackend.org/dreamcode.html. Look for 'To add your dreamcode, follow these instructions.' The link provided in the text is broken.

Link is https://dl.dropboxusercontent.com/u/732913/dream-code.mov. Returns 404.

**Comment by gr2m** [comment]
Thanks @samyakbhuta, that was a video living in my drop box, I had removed it by accident I guess. If you want to add a dreamcode to the list, just create a gist and let me know the link, I'll add it

**Comment by samyakbhuta** [comment]
Sure. I shall be putting few snippets for sure. On the other note, all the
commits and discussion are 6 months old. Is anybody working on this ?

**Comment by gr2m** [comment]
Yes, this is more up-to-date than ever. The attention in terms of visitors and feedback for the overall concept of dreamcode increases. The problem is that we use GitHub gists, which is simple to setup, but not helpful when it comes to discussions, as it doesn't even support notifications or pull requests.

I started working on a better UI for it at http://dreamcode.io/, but didn't get very far just yet :)
